#  ___                     _
# |_ _|___  ___  _____   _| | ____ _
#  | |/ _ \/ __|/ _ \ \ / / |/ / _` |
#  | | (_) \__ \  __/\ V /|   < (_| |
# |___\___/|___/\___| \_/ |_|\_\__,_|
#

[iosevka]
build_plans = ["IosevkaCustomMono", "IosevkaCustomPropo"]
build_plans_file = "contrib/iosevka/private-build-plans.toml"
vendor_dir = "vendor/iosevka/"
font_version = "33.2.7"

[iosevka.subsetting]
build_suffix = 1
subsets_config = "contrib/iosevka/subsets.toml"
font_sample = "vendor/iosevka/dist/IosevkaCustomMono/WOFF2/IosevkaCustomMono-Regular.woff2"
css_base_url = "/fonts/"
output_dir = "public/fonts/"
