### See https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md for comprehensive
### documentation of the options in this file
#
#  ___                     _            ____          _
# |_ _|___  ___  _____   _| | ____ _   / ___|   _ ___| |_ ___  _ __ ___
#  | |/ _ \/ __|/ _ \ \ / / |/ / _` | | |  | | | / __| __/ _ \| '_ ` _ \
#  | | (_) \__ \  __/\ V /|   < (_| | | |__| |_| \__ \ || (_) | | | | | |
# |___\___/|___/\___| \_/ |_|\_\__,_|  \____\__,_|___/\__\___/|_| |_| |_|
#
#  ____
# | __ )  __ _ ___  ___
# |  _ \ / _` / __|/ _ \
# | |_) | (_| \__ \  __/
# |____/ \__,_|___/\___|
#
#
[buildPlans.IosevkaCustomBase]
family = "Iosevka Custom Base"

###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would be built and mapped to
# default values.
# IMPORTANT: Currently "menu" and "css" properties only support numbers between 0 and 1000
#            and "shape" properly only support numbers between 100 and 900 (inclusive).
#            If you decide to use custom weights, you have to define all the weights you
#            plan to use otherwise they will not be built.

[buildPlans.IosevkaCustomBase.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.IosevkaCustomBase.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaCustomBase.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCustomBase.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomBase.weights.Book]
shape = 450
menu = 450
css = 450

[buildPlans.IosevkaCustomBase.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCustomBase.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCustomBase.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomBase.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaCustomBase.weights.Heavy]
shape = 900
menu = 900
css = 900

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# When this section is absent, all slopes would be built.

[buildPlans.IosevkaCustomBase.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

#[buildPlans.IosevkaCustom.slopes.Oblique]
#angle = 9.4
#shape = "oblique"
#menu = "oblique"
#css = "oblique"

[buildPlans.IosevkaCustomBase.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

# End slope section
###################################################################################################
#
#  ___                     _            ____          _
# |_ _|___  ___  _____   _| | ____ _   / ___|   _ ___| |_ ___  _ __ ___
#  | |/ _ \/ __|/ _ \ \ / / |/ / _` | | |  | | | / __| __/ _ \| '_ ` _ \
#  | | (_) \__ \  __/\ V /|   < (_| | | |__| |_| \__ \ || (_) | | | | | |
# |___\___/|___/\___| \_/ |_|\_\__,_|  \____\__,_|___/\__\___/|_| |_| |_|
#
#  ____
# |  _ \ _ __ ___  _ __   ___
# | |_) | '__/ _ \| '_ \ / _ \
# |  __/| | | (_) | |_) | (_) |
# |_|   |_|  \___/| .__/ \___/
#                 |_|
#
[buildPlans.IosevkaCustomPropo]
family = "Iosevka Custom Propo"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
noLigation = true
exportGlyphNames = false
#webfontFormats = ["woff2"]

variants.inherits = "ss03"
weights.inherits = "buildPlans.IosevkaCustomBase"
slopes.inherits = "buildPlans.IosevkaCustomBase"

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would be built and mapped to
# default values.
# IMPORTANT: Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#            while "menu" only supports integers between 1 and 9 (inclusive).
#            The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#            widths are equal to, or a simple multiple of the unit width.
#            If you decide to use custom widths, you have to define all the widths you plan to use.
#            Otherwise, they will not be built.

[buildPlans.IosevkaCustomPropo.widths.Normal]
shape = 500
menu = 5
css = "normal"

#  ___                     _            ____          _
# |_ _|___  ___  _____   _| | ____ _   / ___|   _ ___| |_ ___  _ __ ___
#  | |/ _ \/ __|/ _ \ \ / / |/ / _` | | |  | | | / __| __/ _ \| '_ ` _ \
#  | | (_) \__ \  __/\ V /|   < (_| | | |__| |_| \__ \ || (_) | | | | | |
# |___\___/|___/\___| \_/ |_|\_\__,_|  \____\__,_|___/\__\___/|_| |_| |_|
#
#  __  __
# |  \/  | ___  _ __   ___
# | |\/| |/ _ \| '_ \ / _ \
# | |  | | (_) | | | | (_) |
# |_|  |_|\___/|_| |_|\___/
#
#
[buildPlans.IosevkaCustomMono]
family = "Iosevka Custom Mono"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
#webfontFormats = ["woff2"]

variants.inherits = "ss07"
weights.inherits = "buildPlans.IosevkaCustomBase"
slopes.inherits = "buildPlans.IosevkaCustomBase"

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would be built and mapped to
# default values.
# IMPORTANT: Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#            while "menu" only supports integers between 1 and 9 (inclusive).
#            The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#            widths are equal to, or a simple multiple of the unit width.
#            If you decide to use custom widths, you have to define all the widths you plan to use.
#            Otherwise, they will not be built.

[buildPlans.IosevkaCustomMono.widths.Normal]
shape = 500
menu = 5
css = "normal"
